---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/Nec2005/concourse-tutorial.git
      branch: dev

  - name: resource-app
    type: git
    source:
      uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-tutorial
        trigger: true
      - get: resource-app
        trigger: true
      - task: web-app-tests
        file: resource-tutorial/tutorials/basic/job-inputs/task_run_tests.yml
