---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/Nec2005/concourse-tutorial.git
      branch: dev
  - name: resource-gist
    type: git
    source:
      branch: main
      uri: https://gist.github.com/de132968254e4f781ae5fe4f4d18e70f.git
      username: Nec2005
      password: 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
      #private_key:

jobs:
  - name: job-bump-date
    serial: true
    plan:
      - get: resource-tutorial
      - get: resource-gist
      - task: bump-timestamp-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}

          inputs:
            - name: resource-tutorial
            - name: resource-gist
          outputs:
            - name: updated-gist
          run:
            path: resource-tutorial/tutorials/basic/publishing-outputs/bump-timestamp-file.sh

      - put: resource-gist
        params:
          repository: updated-gist
