---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/Nec2005/concourse-tutorial.git
      branch: dev

jobs:
  - name: job-pass-files
    public: true
    plan:
      - get: resource-tutorial
      - task: create-new-folder
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}

          inputs:
            - name: resource-tutorial
          outputs:
            - name: myfolder

          run:
            path: resource-tutorial/tutorials/basic/task-outputs-to-inputs/create_some_files.sh

      - task: show-myfolder
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: busybox}

          inputs:
            - name: resource-tutorial
            - name: myfolder

          run:
            path: resource-tutorial/tutorials/basic/task-outputs-to-inputs/show_files.sh
