---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/Nec2005/concourse-tutorial.git
      branch: dev

  - name: hello-world-registry-image
    type: registry-image
    source:
      #email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((appname))

jobs:
  - name: build-and-push
    public: true
    plan:
      - get: tutorial
      - put: hello-world-registry-image
        params:
          build: tutorial/tutorials/miscellaneous/registry-images/docker
      - task: run
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((docker-hub-username))/((appname))
          run:
            path: /bin/hello-world
            args: []
          params:
            NAME: ((docker-hub-username))
